Vagrant.configure("2") do |config|

  config.vm.provider :azure do |azure, override|
    azure.location="westeurope"
    azure.resource_group_name="CCGroupEU"

    azure.vm_image_urn="credativ:Debian:8:latest"

    azure.tenant_id = ENV['AZURE_TENANT_ID']
    azure.client_id = ENV['AZURE_CLIENT_ID']
    azure.client_secret = ENV['AZURE_CLIENT_SECRET']
    azure.subscription_id = ENV['AZURE_SUBSCRIPTION_ID']
  end

  config.vm.define "serviceObjectData" do |serviceObject|
    serviceObject.vm.box = 'azure'
    serviceObject.ssh.private_key_path = '~/.ssh/id_rsa'

    serviceObject.vm.provider :azure do |azure, override|
      azure.vm_name="serviceObjectMachine"
    end

  end

  config.vm.define "serviceImageData" do |serviceImage|
    serviceImage.vm.box = 'azure'
    serviceImage.ssh.private_key_path = '~/.ssh/id_rsa'

    serviceImage.vm.provider :azure do |azure, override|
      azure.vm_name="serviceImageMachine"
    end

  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provision.yml"
  end

end
