Vagrant.configure("2") do |config|

  config.vm.provider :azure do |azure, override|
    azure.location="westeurope"
    azure.resource_group_name="CCGroupEU"

    azure.vm_image_urn="credativ:Debian:8:latest"

    azure.tenant_id = "c4fdfd49-2e3f-499c-a883-07f5b579d63f"
    azure.client_id = "b27b2c9b-7674-4544-b532-690dd23e9619"
    azure.client_secret = "9fab1b31-f54d-414f-90a4-d646de2a3b61"
    azure.subscription_id = "60805b7d-7e91-43e9-b534-26417d4a711b"
  end

  config.vm.define "serviceObjectData" do |serviceObject|
    serviceObject.vm.box = 'azure'
    serviceObject.ssh.private_key_path = '~/.ssh/id_rsa'

    serviceObject.vm.provider :azure do |azure, override|
      azure.vm_name="serviceObjectMachine"
    end

  end

  config.vm.define "serviceImageData" do |serviceImage|
    serviceImage.vm.box = 'azure'
    serviceImage.ssh.private_key_path = '~/.ssh/id_rsa'

    serviceImage.vm.provider :azure do |azure, override|
      azure.vm_name="serviceImageMachine"
    end

  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provision.yml"
  end

end
