#Variables
tenant_id = ENV['AZURE_TENANT_ID']
client_id = ENV['AZURE_CLIENT_ID']
client_secret = ENV['AZURE_CLIENT_SECRET']
subscription_id = ENV['AZURE_SUBSCRIPTION_ID']

Vagrant.configure("2") do |config|
  config.vm.define "serviceObjectData" do |serviceObject|
    serviceObject.vm.box = 'azure'

    serviceObject.ssh.private_key_path = '~/.ssh/id_rsa'

    serviceObject.vm.provider :azure do |azure, override|
      azure.location="westeurope"

      azure.resource_group_name="CCGroupEU"
      azure.vm_name="serviceObjectMachine"

      azure.vm_image_urn="credativ:Debian:8:latest"

      azure.tenant_id = tenant_id
      azure.client_id = client_id
      azure.client_secret = client_secret
      azure.subscription_id = subscription_id
    end

  end

  config.vm.define "serviceImageData" do |serviceImage|
    serviceImage.vm.box = 'azure'

    serviceImage.ssh.private_key_path = '~/.ssh/id_rsa'

    serviceImage.vm.provider :azure do |azure, override|
      azure.location="westeurope"

      azure.resource_group_name="CCGroupEU"
      azure.vm_name="serviceImageMachine"

      azure.vm_image_urn="credativ:Debian:8:latest"

      azure.tenant_id = tenant_id
      azure.client_id = client_id
      azure.client_secret = client_secret
      azure.subscription_id = subscription_id
    end

  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provision.yml"
  end

end
